echo ""
echo "     .--------."
echo "    / .------. \ "
echo "   / /        \ \ "
echo "   | |        | |"
echo "  _| |________| |_"
echo " .' |_|        |_| '."
echo " '._____ ____ _____.'"
echo " |     .'____'.     |"
echo " '.__.'.'    '.'.__.''"
echo " '.__  |TURING|  __.'"
echo " |   '.'.____.'.'   | CLI Password Manager"
echo " '.____'.____.'____.' by Daniel Salvaloza"
echo " '.________________.'"
echo ""
