# Source files 
source shell/kdf.sh 
source shell/kdf_src.sh

exec_genSHA256()
{
	# $1 as $pphrase
	# $2 as $SHA256
	# $3 as $salt_buf
	
	# Call functions for SHA256 digestion  
	exec_pphrase = $(prompt/get_pphrase.sh)
	if[-z "$2"]; then 
		echo "ERR: pphrase shouldnt be empty"
		echo  

	gcc -o salt_exec src/main.c

	# $salt_buf will RAND generated bytes from main function  
	./salt_exec $3 

	if[-z "$3"]; then 
		echo "ERR: salt_gen"
		echo  

	exec_kdf = $(shell/kdf.sh $1 $2 $3)
	
	if[-z "$1"]; then 
		echo "ERR: SHA256"
		echo  
}

exec_genSHA256 "$pphrase" "$SHA256" "$salt_buf"






