
source shell/kdf.sh 
source shell/kdf_src.sh

exec_salt()
{
	do_get_salt_exec = $(gcc -o salt_exec src/main.c)
	
	salt_buf = ""

	# $salt_buf will RAND generated bytes from main function  
	./salt_exec $salt_buf 
}

exec_get_pphrase()
{
	exec_pphrase = $(prompt/get_pphrase.sh)
}

exec_digestSHA256()
{
	exec_pphrase = $(shell/kdf.sh)
}_

exec_genSHA256()
{
	# Call function in order to gen SHA256 
	exec_get_pphrase
	exec_salt
	exec_digestSHA256
}

exec_genSHA256






